apiVersion: v2
name: rdbms
version: 0.8.0-13
appVersion: "2.0"
description: This helm chart allows deploying a database engine, which can be either PostgreSQL or MariaDB.
deprecated: true
keywords:
  - postgres
  - mysql
  - mariadb
  - database
  - sql        
sources:
  - https://github.com/ArkCase/ark_helm_charts
dependencies:
  - name: common
    version: ~0.8.0
    repository: "https://arkcase.github.io/ark_helm_charts"
