{{- $content := (include "arkcase.cm.info" $ | fromYaml) }}
defaults:
  acl: "private"

  # This is an alternate syntax to abbreviate only enabling versioning,
  # but not enabling MFA Deletion
  version: true

# List of S3 buckets to create
buckets:

  # Key = bucket name, value = bucket configuration
  "@env:ARKCASE_CONTENT_BUCKET":
    # If acl is not given, the default value will be "private"
    # Must be one of private, public-read, public-read-write, authenticated-read
    acl: "private"

    # The versioning configuration requires at most two boolean values:
    #   mfaDel - enable deletion using MFA
    #   enable - whether to enable versioning on the bucket
    # version:
    #   mfaDel: true
    #   enable: true
