{{- if and (include "arkcase.subsystem.enabled" $) (not (include "arkcase.subsystem.external" $)) }}
  {{- $cluster := (include "arkcase.cluster" $ | fromYaml) }}
  {{- $replicas := ($cluster.replicas | int) -}}
  {{- if (gt $replicas 1) -}}
    {{- $maxUnavailable := (include "arkcase.solr.maxUnavailable" ($replicas | int)) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "arkcase.fullname" $ | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  maxUnavailable: {{ $maxUnavailable | quote }}
  selector:
    matchLabels: {{- include "arkcase.labels.matchLabels" $ | nindent 6 }}
  {{- end -}}
{{- end -}}
