apiVersion: v2
name: core
version: 0.8.0-79
appVersion: "3.0.0"
description: A Helm chart for core ArkCase and ConfigServer
type: application
deprecated: true
dependencies:
  - name: common
    version: ~0.8.0
    repository: "https://arkcase.github.io/ark_helm_charts"
