apiVersion: v2
name: core
version: 0.10.0-5
appVersion: "4.0.0"
description: A Helm chart for core ArkCase and the Portal
type: application
dependencies:
  - name: common
    version: ~0.10.0-0
    repository: "https://arkcase.github.io/ark_helm_charts"
