apiVersion: v2
name: acme
version: 0.10.0-0
appVersion: "0.28.4"
description: A Helm chart for Step-CA as used by ArkCase
type: application
dependencies:
  - name: common
    version: ~0.10.0-0
    repository: "https://arkcase.github.io/ark_helm_charts"
