apiVersion: v2
name: acme
version: 0.8.0-12
appVersion: "0.29.0"
description: A Helm chart for Step-CA as used by ArkCase
type: application
deprecated: true
dependencies:
  - name: common
    version: ~0.8.0
    repository: "https://arkcase.github.io/ark_helm_charts"
