apiVersion: v2
name: messaging
version: 0.10.0-0
appVersion: "2.42.0"
description: Helm chart for Apache Artemis as used by ArkCase
keywords:
  - artemis
  - message broker
sources:
  - https://github.com/ArkCase/ark_helm_charts
dependencies:
  - name: common
    version: ~0.10.0-0
    repository: "https://arkcase.github.io/ark_helm_charts"
