apiVersion: v2
name: ldap
version: 0.10.0-2
appVersion: "latest"
description: A Helm chart for Samba 4 as used by ArkCase
type: application
dependencies:
  - name: common
    version: ~0.10.0-0
    repository: "https://arkcase.github.io/ark_helm_charts"
