apiVersion: v2
name: search
version: 0.10.0-0
appVersion: "9.9.0"
description: A Helm chart for Solr as used by ArkCase
type: application
dependencies:
  - name: common
    version: ~0.10.0-0
    repository: "https://arkcase.github.io/ark_helm_charts"
