apiVersion: v2
name: zookeeper
version: 0.8.0-10
appVersion: "3.8.5"
description: A Helm chart for ZooKeeper as used by ArkCase
type: application
deprecated: true
dependencies:
  - name: common
    version: ~0.8.0
    repository: "https://arkcase.github.io/ark_helm_charts"
