apiVersion: v2
name: analytics
version: 0.8.0-5
appVersion: "4.4.33"
description: A Helm chart for Neo4J as used by ArkCase
type: application
deprecated: true
dependencies:
  - name: common
    version: ~0.8.0
    repository: "https://arkcase.github.io/ark_helm_charts"
