apiVersion: v2
name: content
version: 0.7.18
appVersion: "2.2.1"
description: A Helm chart for deploying Content Storage Services as used by ArkCase (Alfresco v7.3.1 or Minio)
keywords:
  - content
  - content services
  - alfresco
  - alfresco content services
  - s3
  - minio
dependencies:
  - name: common
    version: ~0.7.0
    repository: "https://arkcase.github.io/ark_helm_charts"
deprecated: true
