{{- if and (include "arkcase.subsystem.enabled" $) (not (include "arkcase.subsystem.external" $)) }}
{{- if $.Values.persistence.enabled }}
{{- $settings := (include "arkcase.persistence.settings" $ | fromYaml) }}
{{- if $settings.enabled }}
{{- $pvcName := (printf "%s-data" (include "arkcase.fullname" $)) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: "tika"
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.persistence.volumeSize.data | default "16Gi" }}
{{- with $settings.storageClassName }}
  storageClassName: {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
