apiVersion: v2
name: tika
version: 0.10.0-0
appVersion: "3.2.3"
description: A Helm chart for Apache Tika Server as used by ArkCase
type: application
dependencies:
  - name: common
    version: ~0.10.0-0
    repository: "https://arkcase.github.io/ark_helm_charts"
