{{- if (include "arkcase.subsystem.enabled" $) -}}
  {{- $ctx := $ -}}
  {{- $name := (include "arkcase.pentaho.license.secret.name" $) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "arkcase.labels" $ | nindent 4 }}
    {{- with ($.Values.labels).common }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with ($.Values.annotations).common }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
{{- $license := (include "arkcase.pentaho.license" $ctx | fromYaml) -}}
{{- if $license -}}
  {{- dict "stringData" (omit $license "file") "data" (pick $license "file") | toYaml | nindent 0 -}}
{{- end -}}
{{- end -}}
